version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Flights
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
      build: .
      restart: always
      environment:
        DB_HOST: db
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: Flights
        DB_PORT: 3306
      ports:
        - "3000:3000"
      depends_on:
        - db
      volumes:
        - ./logs:/usr/src/app/logs

volumes:
  db_data: